server {
    listen 8088;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Configuration pour les fichiers statiques
    location / {
        try_files $uri $uri/ =404;
    }

    # En-têtes CORS et cache
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires 0;
}
